"""Update user last login

Revision ID: 88091284ffb1
Revises: 17dd08661925
Create Date: 2022-07-15 10:03:04.599572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88091284ffb1'
down_revision = '17dd08661925'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    # ### end Alembic commands ###
